# Run this first cell to define all the functions:

In [2]:
import financialmath as FM

# 2 securities (K1 and K2), 3 scenarios ==> find everthing else

In [ ]:
p = ["0.2", "0.4", "0.4"]
k1 = ["-0.1", "0","0.1"]
k2 = ["0.05", "0.1", "-0.05"]

FM.two_securities(p, k1, k2)

# HW8 question 1

In [ ]:
# w1, w2, ...., wm
weights = [0.3, 0.1, 0.6]
means = [0.08, 0.1, 0.06]
stdDevs = [0.15, 0.05, 0.12]

# each entry represent correlation of (i, j) ans stored in the form [(i, j), value]
correlation = [
    [[1, 2], 0.3],
    [[2, 3], 0],
    [[1, 3], -0.2],
]


mu_V = meanV(weights, means) 
cMatrix = makeCMatrix(correlation, stdDevs)
wCwT = find_wCwT(weights, cMatrix)
np.set_printoptions(suppress=True)
print("Expected value of portfolio is:", mu_V)
print("Correlation matrix is:")
print(np.array(cMatrix))
print("w*C*wT is: ", wCwT)
print("stdDev of portfolio is", math.sqrt(wCwT))
print("\n", "*"* 20, "\n")
cInverse = np.linalg.inv(cMatrix)
print("here is the inverse of C:")
print(cInverse)
m = np.array(means)
u = np.array([1 for _ in means])
print("m is:", m)
print("u is:", u)
print("calculating M")
Mmatrix = makeM(m, cInverse, u)
print("here is M:")
print(Mmatrix)
print("here is M inverse:")
MmatrixInv = np.linalg.inv(Mmatrix)
print(MmatrixInv)

# HW 7 Part 2:

In [ ]:
m = [0.2, 0.13, 0.17]
stdDevs = [0.25, 0.28, 0.20]
correlation= [
    [[1,2], 0.25],
    [[2,3], 0],
    [[3,1], 0.15]]

find_W_MVP(m, stdDevs, correlation)

# HW 8, Problem 3:

In [ ]:
m = [0.2, 0.1, 0.2]
stdDevs = [0.25, 0.2, 0.25]
correlation= [
    [[1,2], 0.25],
    [[2,3], 0.05],
    [[3,1], 0.15]]

FM.find_W_MVP(m, stdDevs, correlation)

# HW 9 Problem 1

In [3]:
mu = [0.2, 0.15, 0.17]
stdevs = [0.25, 0.28, 0.2]
corr = [
    [[1, 2],0.25],
    [[2,3], 0.0],
    [[1, 3], 0.15]
    ]
muV = 0.2

x = FM.portfolio_MVP(mu, stdevs, corr)
x.W_MVP_Given_Ev(muV)

m is: [0.2  0.15 0.17] 
u is: [1 1 1]

C matrix is:
[[0.0625 0.0175 0.0075]
 [0.0175 0.0784 0.    ]
 [0.0075 0.     0.04  ]]

here is the inverse of C:
 [[17.4863388  -3.90320062 -3.27868852]
 [-3.90320062 13.62635218  0.73185012]
 [-3.27868852  0.73185012 25.6147541 ]]

calculating M:
Intermediate Calculations:
M*C^-1 =  [2.35441062 1.38772722 3.80854801]
u*C^-1 =  [10.30444965 10.45500167 23.06791569]

here is M:
[[ 1.32649437  7.55068585]
 [ 7.55068585 43.82736701]]

here is M inverse:
[[38.99583251 -6.71829728]
 [-6.71829728  1.18026146]]

The weight in minimum variance portfolio is:
[0.2351145  0.23854962 0.52633588]

The Expected return of the MVP is:
0.17228244274809162

Variance is:
intermediate calculation: w*C =  [0.02281679 0.02281679 0.02281679]
wCwT = Varinace = 
0.022816793893129773

The Std.Dev of the portfolio is:
0.1510522886060644
********************
********************

calculating for a and b:
[a, b].T = M^-1 * [m, u].T * C^-1
this is vector a:  [ 22.583846 -16.12

# HW 9 Problem 2:

In [2]:
mu = [0.16, 0.13, 0.13]
stdevs = [0.25, 0.28, 0.2]
corr = [
    [[1, 2],0.3],
    [[2,3], 0.0],
    [[1, 3], 0.15]
    ]

x = FM.portfolio_MVP(mu, stdevs, corr)
x.calculate_ab()
x.calculate_MVL_slope(2, 3)

m is: [0.16 0.13 0.13] 
u is: [1 1 1]

C matrix is:
[[0.0625 0.021  0.0075]
 [0.021  0.0784 0.    ]
 [0.0075 0.     0.04  ]]

here is the inverse of C:
 [[18.02816901 -4.82897384 -3.38028169]
 [-4.82897384 14.04857718  0.9054326 ]
 [-3.38028169  0.9054326  25.63380282]]

calculating M:
Intermediate Calculations:
M*C^-1 =  [1.81730382 1.17138546 2.90925553]
u*C^-1 =  [ 9.81891348 10.12503593 23.15895372]

here is M:
[[ 0.82125194  5.89794481]
 [ 5.89794481 43.10290313]]

here is M inverse:
[[70.36176802 -9.6278857 ]
 [-9.6278857   1.34062289]]

The weight in minimum variance portfolio is:
[0.22780167 0.2349038  0.53729452]

The Expected return of the MVP is:
0.1368340502150645

Variance is:
intermediate calculation: w*C =  [0.02320029 0.02320029 0.02320029]
wCwT = Varinace = 
0.023200293421359743

The Std.Dev of the portfolio is:
0.1523164253170345
********************

calculating for a and b:
[a, b].T = M^-1 * [m, u].T * C^-1
this is vector a:  [ 33.33333333 -15.06193694 -18.2713964 ]

# HW 9 part 3:

In [5]:
mu = [0.08, 0.1, 0.06]
stdevs = [0.15, 0.05, 0.12]
corr = [
    [[1, 2],0.3],
    [[2,3], 0.0],
    [[1, 3], -0.2]
    ]
risk_free_rate = 0.05
x = FM.portfolio_MVP(mu, stdevs, corr)
print("\nbelow is the work for the market portfolio")
x.market_portfolio(risk_free_rate)
print("*"*20)

m is: [0.08 0.1  0.06] 
u is: [1 1 1]

C matrix is:
[[ 0.0225   0.00225 -0.0036 ]
 [ 0.00225  0.0025   0.     ]
 [-0.0036   0.       0.0144 ]]

here is the inverse of C:
 [[ 51.08556833 -45.97701149  12.77139208]
 [-45.97701149 441.37931034 -11.49425287]
 [ 12.77139208 -11.49425287  72.63729246]]

calculating M:
Intermediate Calculations:
M*C^-1 =  [ 0.25542784 39.77011494  4.23052363]
u*C^-1 =  [ 17.87994891 383.90804598  73.91443167]

here is M:
[[  4.25127714  44.25606641]
 [ 44.25606641 475.70242656]]

here is M inverse:
[[ 7.46276714 -0.69428428]
 [-0.69428428  0.06669357]]

The weight in minimum variance portfolio is:
[0.03758642 0.80703403 0.15537956]

The Expected return of the MVP is:
0.0930330894690919

Variance is:
intermediate calculation: w*C =  [0.00210215 0.00210215 0.00210215]
wCwT = Varinace = 
0.0021021545070138946

The Std.Dev of the portfolio is:
0.045849258521964066

below is the work for the market portfolio
********************

weights in a market portfolio = ((